# Generated by Django 2.2.16 on 2021-03-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_geography'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geography',
            options={'verbose_name_plural': 'Geographies'},
        ),
        migrations.AlterField(
            model_name='geography',
            name='boundary_file',
            field=models.FileField(blank=True, null=True, upload_to='boundary/'),
        ),
    ]
