# Generated by Django 2.2.16 on 2021-03-30 06:56

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom', '0003_auto_20210330_0548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('name_long', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('domain', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('domain_init', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('colorstops', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('raster', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('vectors', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('csv', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('analysis', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('timeline', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('controls', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'path': [], 'range': '', 'range_label': '', 'range_steps': '', 'weight': False}, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'why': ''}, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('name_long', models.TextField(blank=True)),
                ('unit', models.TextField(blank=True)),
                ('pack', models.CharField(blank=True, default='all', max_length=50)),
                ('circle', models.CharField(blank=True, default='public', max_length=50)),
                ('online', models.BooleanField(default=True)),
                ('presets', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('configuration', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('category_overrides', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'cautions': '', 'content_date': '', 'description': '', 'download_original_url': '', 'learn_more_url': '', 'license': '', 'sources': '', 'spatial_resolution': '', 'suggested_citation': ''})),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom.Category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Geographies',
            },
        ),
        migrations.AlterField(
            model_name='geography',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geography_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='geography',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geography_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DatasetFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.FileField(upload_to='datasets/')),
                ('label', models.CharField(max_length=100)),
                ('configuration', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('test', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=False)),
                ('func', models.CharField(blank=True, choices=[('csv', 'CSV'), ('vectors', 'Vectors'), ('raster', 'Raster')], default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset_file_created_by', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom.Dataset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset_file_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='geography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom.Geography'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
