# Generated by Django 2.2.16 on 2021-03-30 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0004_auto_20210330_0656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='dataset',
            options={'verbose_name_plural': 'Datasets'},
        ),
        migrations.AlterModelOptions(
            name='datasetfile',
            options={'verbose_name_plural': 'Dataset Files'},
        ),
    ]
