# Generated by Django 2.2.16 on 2021-04-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0006_auto_20210405_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetfile',
            name='func',
            field=models.CharField(blank=True, choices=[('csv', 'CSV'), ('vectors', 'Vectors'), ('raster', 'Raster')], default='', max_length=50, verbose_name='Dataset File Type'),
        ),
    ]
