# Generated by Django 2.2.16 on 2021-04-27 01:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0007_auto_20210424_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetfile',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='datasetfile',
            name='test',
        ),
        migrations.AddField(
            model_name='category',
            name='circle',
            field=models.CharField(blank=True, default='public', max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='configuration',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='geography',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.Geography'),
        ),
        migrations.AddField(
            model_name='category',
            name='online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='pack',
            field=models.CharField(blank=True, default='all', max_length=50),
        ),
        migrations.AddField(
            model_name='datasetfile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'cautions': '', 'content_date': '', 'description': '', 'download_original_url': '', 'learn_more_url': '', 'license': '', 'sources': '', 'spatial_resolution': '', 'suggested_citation': ''}),
        ),
        migrations.AlterField(
            model_name='datasetfile',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
