# Generated by Django 2.2.16 on 2021-04-27 05:55

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_auto_20181220_0803'),
        ('custom', '0010_auto_20210427_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCAPreferences',
            fields=[
                ('preferences_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='preferences.Preferences')),
                ('boundary_dimension_x', models.FloatField(default=100)),
                ('boundary_dimension_y', models.FloatField(default=100)),
            ],
            bases=('preferences.preferences',),
            managers=[
                ('singleton', django.db.models.manager.Manager()),
            ],
        ),
    ]
