# Generated by Django 2.2.16 on 2021-04-27 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0011_ccapreferences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ccapreferences',
            options={'verbose_name_plural': 'CCA Preferences'},
        ),
    ]
