# Generated by Django 2.2.16 on 2021-05-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0013_auto_20210505_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AlterField(
            model_name='category',
            name='name_long',
            field=models.TextField(blank=True, verbose_name='Name'),
        ),
    ]
