# Generated by Django 2.2.16 on 2021-05-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0014_auto_20210505_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='boundary_layer',
            field=models.BooleanField(default=False),
        ),
    ]
