# Generated by Django 2.2.16 on 2021-05-11 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0016_category_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name_plural': 'Categories'},
        ),
    ]
