# Generated by Django 2.2.16 on 2021-05-17 07:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0020_auto_20210517_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='controls',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'path': [], 'range': 'double', 'range_label': '', 'range_steps': '', 'weight': False}, null=True),
        ),
    ]
