# Generated by Django 2.2.16 on 2021-05-24 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0023_mainmenu_submenu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainmenu',
            options={'ordering': ['order'], 'verbose_name_plural': 'Main menu'},
        ),
        migrations.AlterModelOptions(
            name='submenu',
            options={'ordering': ['order'], 'verbose_name_plural': 'Sub menu'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='sidebar_main_menu',
        ),
        migrations.RemoveField(
            model_name='category',
            name='sidebar_sub_menu',
        ),
        migrations.AddField(
            model_name='category',
            name='sidebar_main_menu_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_sidebar_main_menu', to='custom.MainMenu'),
        ),
        migrations.AddField(
            model_name='category',
            name='sidebar_sub_menu_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_sidebar_main_menu', to='custom.SubMenu'),
        ),
    ]
