# Generated by Django 2.2.16 on 2021-05-27 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0025_auto_20210524_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sidebar_sub_menu_obj',
            field=models.ForeignKey(blank=True, help_text='[Main Menu] - Sub Menu', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_sidebar_sub_menu', to='custom.SubMenu', verbose_name='Sidebar menu'),
        ),
    ]
