# Generated by Django 2.2.16 on 2021-06-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0026_auto_20210527_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetfile',
            name='label',
            field=models.CharField(default='', max_length=100),
        ),
    ]
