# Generated by Django 2.2.16 on 2021-06-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0027_auto_20210609_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ccapreferences',
            name='boundary_dimension_x',
        ),
        migrations.RemoveField(
            model_name='ccapreferences',
            name='boundary_dimension_y',
        ),
        migrations.AddField(
            model_name='geography',
            name='boundary_dimension_x',
            field=models.FloatField(default=100, help_text='Raster resolution (x)'),
        ),
        migrations.AddField(
            model_name='geography',
            name='boundary_dimension_y',
            field=models.FloatField(default=100, help_text='Raster resolution (y)'),
        ),
    ]
