# Generated by Django 2.2.16 on 2021-06-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0028_auto_20210614_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='weight',
            field=models.BooleanField(default=True),
        ),
    ]
