# Generated by Django 2.2.16 on 2021-06-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0029_category_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='controls',
        ),
        migrations.AddField(
            model_name='category',
            name='range_type',
            field=models.CharField(blank=True, default='', help_text='Range data type, e.g. double', max_length=128),
        ),
        migrations.AlterField(
            model_name='category',
            name='legend_range_steps',
            field=models.IntegerField(blank=True, null=True, verbose_name='Range steps'),
        ),
    ]
