# Generated by Django 2.2.16 on 2021-06-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0030_auto_20210614_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ani_index',
            field=models.BooleanField(default=False, help_text='The Assistance Need Index identifies areas where market assistance is needed the most which are characterized with higher index values. It is an aggregated and weighted measure of selected data sets under both Demand and Supply categories indicating high energy demand, low economic activity, and low access to infrastructure and resources.', verbose_name='Use Assistance Need Index'),
        ),
        migrations.AddField(
            model_name='category',
            name='ani_invert',
            field=models.BooleanField(default=False, verbose_name='Invert'),
        ),
        migrations.AddField(
            model_name='category',
            name='ani_scale',
            field=models.CharField(blank=True, choices=[('linear', 'Linear'), ('intervals', 'Intervals'), ('key-delta', 'Key Delta'), ('inclusion-buffer', 'Inclusion Buffer')], default='', max_length=50, verbose_name='ANI Scale'),
        ),
        migrations.AddField(
            model_name='category',
            name='demand_index',
            field=models.BooleanField(default=False, help_text='The Demand Index identifies areas with higher energy demand which are characterized with higher index values. It is an aggregated and weighted measure of all selected data sets under Demographics and Socio-economic activities.', verbose_name='Use Demand'),
        ),
        migrations.AddField(
            model_name='category',
            name='demand_invert',
            field=models.BooleanField(default=False, verbose_name='Invert'),
        ),
        migrations.AddField(
            model_name='category',
            name='demand_scale',
            field=models.CharField(blank=True, choices=[('linear', 'Linear'), ('intervals', 'Intervals'), ('key-delta', 'Key Delta'), ('inclusion-buffer', 'Inclusion Buffer')], default='', max_length=50, verbose_name='Demand Scale'),
        ),
        migrations.AddField(
            model_name='category',
            name='eap_invert',
            field=models.BooleanField(default=False, verbose_name='Invert'),
        ),
        migrations.AddField(
            model_name='category',
            name='eap_scale',
            field=models.CharField(blank=True, choices=[('linear', 'Linear'), ('intervals', 'Intervals'), ('key-delta', 'Key Delta'), ('inclusion-buffer', 'Inclusion Buffer')], default='', max_length=50, verbose_name='EAP Scale'),
        ),
        migrations.AddField(
            model_name='category',
            name='eap_use',
            field=models.BooleanField(default=False, help_text='The Energy Access Potential Index identifies areas with higher energy demand and supply which are characterized with higher index values. It is an aggregated measure of all selected data sets under both Demand and Supply categories.', verbose_name='Use Energy Access Potential'),
        ),
        migrations.AddField(
            model_name='category',
            name='supply_index',
            field=models.BooleanField(default=False, help_text='The Supply Index identifies areas with higher energy supply which are characterized with higher index values. It is an aggregated and weighted measure of all selected data sets under Resource Availability and Infrastructure.', verbose_name='Use Supply'),
        ),
        migrations.AddField(
            model_name='category',
            name='supply_invert',
            field=models.BooleanField(default=False, verbose_name='Invert'),
        ),
        migrations.AddField(
            model_name='category',
            name='supply_scale',
            field=models.CharField(blank=True, choices=[('linear', 'Linear'), ('intervals', 'Intervals'), ('key-delta', 'Key Delta'), ('inclusion-buffer', 'Inclusion Buffer')], default='', max_length=50, verbose_name='Supply Scale'),
        ),
    ]
