# Generated by Django 2.2.16 on 2021-06-14 06:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0031_auto_20210614_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='configuration',
        ),
        migrations.AlterField(
            model_name='category',
            name='analysis',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'clamp': False, 'index': 'supply', 'indexes': [], 'intervals': {}, 'scale': 'linear', 'weight': 2}, null=True),
        ),
    ]
