# Generated by Django 2.2.16 on 2021-06-14 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0032_auto_20210614_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geography',
            name='cca3',
            field=models.CharField(help_text='Three-letter country code', max_length=3, verbose_name='ISO 3 Letter Country Code'),
        ),
        migrations.AlterField(
            model_name='geography',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geography_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='geography',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geography_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
