# Generated by Django 2.2.16 on 2021-10-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0034_auto_20210614_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='geography',
            name='district_selector',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='geography',
            name='municipal_selector',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='geography',
            name='province_selector',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
    ]
