# Generated by Django 2.2.16 on 2021-10-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0035_auto_20211004_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('permalink', models.URLField(default='', verbose_name='Permalink Snippet')),
                ('image', models.ImageField(blank=True, null=True, upload_to='presets')),
            ],
        ),
    ]
