# Generated by Django 2.2.16 on 2021-10-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0036_preset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preset',
            options={'ordering': ['order'], 'verbose_name_plural': 'Presets'},
        ),
        migrations.AddField(
            model_name='preset',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
