# Generated by Django 2.2.16 on 2021-10-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0037_auto_20211005_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('presets', models.ManyToManyField(to='custom.Preset')),
            ],
            options={
                'verbose_name_plural': 'Use Cases',
                'ordering': ['order'],
            },
        ),
    ]
