# Generated by Django 2.2.16 on 2021-11-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0039_clippedlayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clippedlayer',
            name='clipped_file',
            field=models.FileField(blank=True, null=True, upload_to='clipped_layers/'),
        ),
    ]
