# Generated by Django 2.2.16 on 2021-11-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0040_auto_20211101_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clippedlayer',
            name='clipped_file',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='clipped_layers/'),
        ),
    ]
