# Generated by Django 2.2.16 on 2021-11-01 05:43

import custom.models.clipped_layer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0041_auto_20211101_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clippedlayer',
            name='clipped_file',
            field=models.FileField(blank=True, max_length=300, null=True, storage=custom.models.clipped_layer.ClippedFileStorage(), upload_to='clipped_layers/'),
        ),
    ]
