# Generated by Django 2.2.16 on 2021-11-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0042_auto_20211101_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='permalink',
            field=models.URLField(default='', max_length=512, verbose_name='Permalink Snippet'),
        ),
    ]
