# Generated by Django 2.2.16 on 2021-11-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0043_auto_20211104_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='legend_range_steps',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='Range steps'),
        ),
        migrations.AlterField(
            model_name='category',
            name='range_type',
            field=models.CharField(blank=True, default='double', help_text='Range data type, e.g. double', max_length=128),
        ),
    ]
