# Generated by Django 2.2.16 on 2021-11-22 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0034_auto_20211122_0346'),
        ('custom', '0045_reportsummary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportSummary',
            new_name='SummaryReportResult',
        ),
        migrations.AlterModelOptions(
            name='summaryreportresult',
            options={'verbose_name_plural': 'Report summaries'},
        ),
    ]
