# Generated by Django 2.2.16 on 2021-11-23 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0045_summaryreportcategory_summaryreportresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summaryreportcategory',
            options={'verbose_name': 'Summary Calculation Category', 'verbose_name_plural': 'Summary Calculation Categories'},
        ),
        migrations.AlterModelOptions(
            name='summaryreportresult',
            options={'verbose_name': 'Summary Calculation Result', 'verbose_name_plural': 'Summary Calculation Results'},
        ),
    ]
