# Generated by Django 2.2.16 on 2021-11-22 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0046_auto_20211122_0801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summaryreportresult',
            options={'verbose_name_plural': 'Summary Report Results'},
        ),
        migrations.RemoveField(
            model_name='summaryreportresult',
            name='name',
        ),
        migrations.RemoveField(
            model_name='summaryreportresult',
            name='preset',
        ),
        migrations.RemoveField(
            model_name='summaryreportresult',
            name='vector_layer',
        ),
        migrations.CreateModel(
            name='SummaryReportCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom.Preset')),
                ('vector_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.Layer')),
            ],
            options={
                'verbose_name_plural': 'Summary Report Categories',
            },
        ),
    ]
