# Generated by Django 2.2.16 on 2021-11-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0047_geography_household_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='geography',
            name='household_layer_field',
            field=models.CharField(blank=True, default='', help_text='Field to get value from household layer', max_length=255),
        ),
    ]
