# Generated by Django 2.2.16 on 2021-11-26 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0048_geography_household_layer_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='geography',
            name='urban_layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urban_layer', to='layers.Layer'),
        ),
        migrations.AddField(
            model_name='geography',
            name='urban_layer_field',
            field=models.CharField(blank=True, default='', help_text='Field to get value from urban layer', max_length=255),
        ),
    ]
