# Generated by Django 2.2.16 on 2021-11-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0049_auto_20211126_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geography',
            name='urban_layer_field',
        ),
        migrations.AddField(
            model_name='summaryreportcategory',
            name='boundary_uuid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
