# Generated by Django 2.2.16 on 2021-11-26 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0050_auto_20211126_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='geography',
            name='cooking_percentage_layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooking_percentage_layer', to='layers.Layer'),
        ),
        migrations.AddField(
            model_name='geography',
            name='cooking_percentage_layer_field',
            field=models.CharField(blank=True, default='', help_text='Field to get value from cooking percentage layer', max_length=255),
        ),
    ]
