# Generated by Django 2.2.16 on 2021-11-26 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0051_auto_20211126_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='geography',
            name='wealth_index_layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wealth_index_layer', to='layers.Layer'),
        ),
    ]
