# Generated by Django 2.2.16 on 2021-11-28 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0052_geography_wealth_index_layer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryReportDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_file', models.FileField(blank=True, null=True, upload_to='summary_raster_file/')),
            ],
        ),
        migrations.RemoveField(
            model_name='summaryreportcategory',
            name='boundary_uuid',
        ),
        migrations.AddField(
            model_name='summaryreportresult',
            name='boundary_uuid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='summaryreportresult',
            name='dataset_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.SummaryReportDataset'),
        ),
    ]
