# Generated by Django 2.2.16 on 2021-11-28 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0053_auto_20211128_0625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summaryreportresult',
            old_name='category',
            new_name='analysis',
        ),
        migrations.RemoveField(
            model_name='summaryreportresult',
            name='raster_file',
        ),
    ]
