# Generated by Django 2.2.16 on 2021-11-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0054_auto_20211128_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaryreportdataset',
            name='dataset_file',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='summary_raster_file/'),
        ),
    ]
