# Generated by Django 2.2.16 on 2021-12-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0055_auto_20211128_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='ani_index',
            field=models.BooleanField(default=False, verbose_name='Use Assistance Need Index'),
        ),
        migrations.AddField(
            model_name='preset',
            name='ccp_use',
            field=models.BooleanField(default=False, verbose_name='Use Clean Cooking Potential Index'),
        ),
        migrations.AddField(
            model_name='preset',
            name='supply_index',
            field=models.BooleanField(default=False, verbose_name='Use Supply Index'),
        ),
    ]
