# Generated by Django 2.2.16 on 2021-12-04 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0056_auto_20211203_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryreportcategory',
            name='analysis',
            field=models.CharField(blank=True, choices=[('ANI', 'ani'), ('CCP', 'ccp'), ('Supply', 'supply')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='summaryreportcategory',
            name='supply_layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supply_layer', to='layers.Layer'),
        ),
        migrations.AlterField(
            model_name='summaryreportcategory',
            name='vector_layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='layers.Layer'),
        ),
    ]
