# Generated by Django 2.2.16 on 2021-12-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0057_auto_20211204_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaryreportcategory',
            name='analysis',
            field=models.CharField(blank=True, choices=[('ani', 'ANI'), ('ccp', 'CCP'), ('supply', 'Supply')], default='', max_length=100),
        ),
    ]
