# Generated by Django 2.2.16 on 2021-12-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0058_auto_20211220_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryreportcategory',
            name='category',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
