# Generated by Django 2.2.16 on 2022-01-11 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0059_summaryreportcategory_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summaryreportcategory',
            options={'verbose_name': 'Summary Report Category', 'verbose_name_plural': 'Summary Report Categories'},
        ),
        migrations.AlterField(
            model_name='summaryreportcategory',
            name='analysis',
            field=models.CharField(blank=True, choices=[('ani', 'ANI'), ('ccp', 'CCP'), ('supply', 'Supply'), ('supply_demand', 'Supply and Demand')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='summaryreportcategory',
            name='supply_layer',
            field=models.ForeignKey(blank=True, help_text='Raster layer used for ANI analysis calculation. e.g. To calculate population in areas close to LPG supply under poverty line, we need to include LPG distance raster layer here.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supply_layer', to='layers.Layer'),
        ),
        migrations.AlterField(
            model_name='summaryreportcategory',
            name='vector_layer',
            field=models.ForeignKey(blank=True, help_text='Vector layer used to query the data. Needed for CCP or Supply analysis.', null=True, on_delete=django.db.models.deletion.CASCADE, to='layers.Layer'),
        ),
    ]
