# Generated by Django 2.2.16 on 2022-01-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0060_auto_20220111_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='clippedlayer',
            name='state',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='clippedlayer',
            name='process_state',
            field=models.CharField(blank=True, default='', help_text='Process ID', max_length=200),
        ),
    ]
