# Generated by Django 2.2.16 on 2022-01-17 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0061_auto_20220115_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preset',
            name='ani_index',
        ),
        migrations.RemoveField(
            model_name='preset',
            name='ccp_use',
        ),
        migrations.RemoveField(
            model_name='preset',
            name='supply_index',
        ),
        migrations.AddField(
            model_name='usecase',
            name='geography',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.Geography'),
        ),
    ]
