# Generated by Django 2.2.16 on 2022-01-19 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0062_auto_20220117_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='map_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('geonode_layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='layers.Layer')),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom.Preset')),
            ],
        ),
    ]
