# Generated by Django 2.2.16 on 2022-01-20 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0064_mapimage_boundary_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapimage',
            options={'ordering': ['created_at']},
        ),
    ]
