# Generated by Django 2.2.16 on 2022-02-22 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0065_auto_20220120_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaryreportcategory',
            name='vector_layer',
            field=models.ForeignKey(blank=True, help_text='Vector layer used to query the data. Needed for CCP or Supply analysis.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vector_layer', to='layers.Layer'),
        ),
    ]
