# Generated by Django 2.2.16 on 2022-03-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0068_auto_20220316_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ani_index',
            field=models.BooleanField(default=False, help_text='The Finance Need Index identifies areas where market assistance is needed the most which are characterized with higher index values. It is an aggregated and weighted measure of selected data sets under both Demand and Supply categories indicating high energy demand, low economic activity, and low access to infrastructure and resources.', verbose_name='Use Finance Need Index'),
        ),
        migrations.AlterField(
            model_name='preset',
            name='population_ani_text',
            field=models.CharField(default='Population with medium to high Finance Needed Index', help_text='Description text in the report', max_length=255),
        ),
    ]
